version: "3"
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=bookstore
    volumes:
      - ./db/mongo/data:/data/db/
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro   
  command:
    build: ./core/bookSetter
    container_name: bookSetter
    ports:
      - "8123:8080"
    depends_on:
      - mongo
  query:
    build: ./core/bookGetter
    container_name: bookGetter
    ports:
      - "8124:8081"
    depends_on:
      - mongo