apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  init-mongo.js: |
    db.createCollection("books")
    db.getCollection('books').insertOne({
      Title: 'TL',
      Author: 'AH'
      });
    db.getCollection('books').insertOne({
      Title: 'TH',
      Author: 'AH'
      });
    db.getCollection('books').insertOne({
      Title: 'TG',
      Author: 'AH'
      });    