apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        selector: mongodb
    spec:
      containers:
      - name: mongodb        
        image: mongo:4.4
        volumeMounts:
        - name: mongodb-scripts
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-scripts
        configMap:
          name: mongodb-configmap
          items:
          - key: init-mongo.js
            path: init-mongo.js
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc