apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-getter
  labels:
    app: book-getter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book-getter
  template:
    metadata:
      annotations:
        prometheus.io/port: "8081"
        prometheus.io/path: "/query/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: book-getter
    spec:
      containers:
      - name: book-getter
        image: chaimakr/book_ms-bookgetter
        imagePullPolicy: Always 
        ports:
        - containerPort: 8081