version: "3"
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: unless-stopped
    ports:
      - 26000:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=bookstore
      - MONGO_DB_USERNAME=user
      - MONGO_DB_PASSWORD=user
    volumes:
      - ./db/mongo/data:/data/db/
      - ./log/mongo/logs:/var/log/mongodb/
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro 

  app:
    build: .
    ports:
      - "8123:8080"
    depends_on:
      - mongo