datadog:
  site: datadoghq.eu
  
  kubelet: 
    tlsVerify: false
  
  logs:
    enabled: true
    containerCollectAll: true
  # otlp:
  #   receiver:
  #     protocols:
  #       grpc:
  #         enabled: true
  #       http:
  #         enabled: true
  apm:
    portEnabled: true
