name: Book Management System CI 
on:
  push:
    branches:
      - main
    paths-ignore:
      - '/README.md'
jobs:
  book-getter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./core/bookGetter
          file: ./core/bookGetter/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/book_ms-bookgetter
  book-setter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./core/bookSetter
          file: ./core/bookSetter/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/book_ms-booksetter