name: Book Management System CI 
on:
  push:
    branches:
      - main
    paths-ignore:
      - '/README.md'
jobs:
  build_and_push_docker_images:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            service: ['bookGetter', 'bookSetter']
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          - name: Set up Docker Build
            uses: docker/setup-buildx-action@v1
          - name: Build and push to DockerHub
            uses: docker/build-push-action@v2
            with:
              context: ./core/${{ matrix.service }}/
              file: ./core/${{ matrix.service }}/Dockerfile
              push: true
              tags: |
                  ${{ secrets.DOCKER_HUB_USERNAME }}/book_ms-${{matrix.service}}